### ISSUE TITLE
SD1.5 Issues?

### ISSUE THREAD

**Issue by PolarisFx** [aegis72/aegisflow#3]
First off.. the SDXL Workflow is flawless, once the models were changed to reflect my model filenames I was able to immediately generate the included prompt. 

However the SD1.5 Version is full of errors, after changing my models the first generation spits out this:

```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/home/polarisfx/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/polarisfx/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/polarisfx/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/polarisfx/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 2211, in sample_adv
    return super().sample(sampler_state, model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative,
  File "/home/polarisfx/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 642, in sample
    samples = sample_latent_image(model, seed, steps, cfg, sampler_name, scheduler, positive, negative,
  File "/home/polarisfx/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 548, in sample_latent_image
    samples = KSamplerAdvanced().sample(model, add_noise, seed, steps, cfg, sampler_name, scheduler,
  File "/home/polarisfx/ComfyUI/nodes.py", line 1271, in sample
    return common_ksampler(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise, disable_noise=disable_noise, start_step=start_at_step, last_step=end_at_step, force_full_denoise=force_full_denoise)
  File "/home/polarisfx/ComfyUI/nodes.py", line 1207, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/home/polarisfx/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)
  File "/home/polarisfx/ComfyUI/comfy/sample.py", line 97, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/polarisfx/ComfyUI/comfy/samplers.py", line 781, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler(), sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/polarisfx/ComfyUI/comfy/samplers.py", line 668, in sample
    pre_run_control(model_wrap, negative + positive)
  File "/home/polarisfx/ComfyUI/comfy/samplers.py", line 484, in pre_run_control
    x[1]['control'].pre_run(model.inner_model.inner_model, percent_to_timestep_function)
  File "/home/polarisfx/ComfyUI/comfy/controlnet.py", line 269, in pre_run
    comfy.utils.set_attr(self.control_model, k, self.control_weights[k].to(dtype).to(comfy.model_management.get_torch_device()))
```

Also the Fans Styler is full of garbage:
![image](https://github.com/aegis72/aegisflow/assets/12600197/6f895eb6-f39b-44e1-9e2a-8b4d9dfd5b71)

These artifacts are in the json file, they're not added by me:
![image](https://github.com/aegis72/aegisflow/assets/12600197/9ea1d19a-d294-4042-b8e3-2996a760a852)

Anyway, thanks for the SDXL workflow, it's great.

Edit: Just to save issues, In the SDXL workflow, when you disable ControlNet you have batch size set to input in the SDXL latent nodes, but you never specified the source. Just switched them back to widget for now.

**Comment by aegis72** [comment]
Hey there! Just to be sure, can you use the following? I think that somehow I may have uploaded an earlier version that did have that error, but I just ran it from a fresh start and it worked as expected. I'm going to recommit the 1.5 version just to be sure: 
![image](https://github.com/aegis72/aegisflow/
[AegisFlow_1.5.json](https://github.com/aegis72/aegisflow/files/13064851/AegisFlow_1.5.json)
assets/118572301/43fed5ef-1c4b-4a91-8f87-5e32b17d9352)

As for FanStyler, that is just how the component loads. I have no idea why it has those odd opening characters, but if you click on the categories, the drop-downs work as expected, as in this gen I just did (same seed/conditioning, but w/ styler enabled):

![image](https://github.com/aegis72/aegisflow/assets/118572301/d82af854-b3d3-4d94-b77a-10c32ecd5598)

**Comment by aegis72** [comment]
Also....make sure all your plug-ins are updated to the latest. I had a few
plug-ins update before release that meant i had to update my workflow to
match.

**Comment by aegis72** [comment]
Seems as if I may have uploaded a WIP version of 1.5, which has that recursion error; it should be fixed.
